// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQDqp8Hi4_RzmiNRHJQR71-bvolBzG-0U',
    appId: '1:676337022607:web:abb4dd102a8a4e5eb9a2fa',
    messagingSenderId: '676337022607',
    projectId: 'horas-v3-500f4',
    authDomain: 'horas-v3-500f4.firebaseapp.com',
    storageBucket: 'horas-v3-500f4.appspot.com',
    measurementId: 'G-LLT7SY6LGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnrAQZxklEM6LWnVFwswQ6PSaXuohzLo',
    appId: '1:676337022607:android:83b2e4b45fceb071b9a2fa',
    messagingSenderId: '676337022607',
    projectId: 'horas-v3-500f4',
    storageBucket: 'horas-v3-500f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyEuhz61qiYVHqa9xYVkIys8dH3UCh-E',
    appId: '1:676337022607:ios:5b60d90564e2f960b9a2fa',
    messagingSenderId: '676337022607',
    projectId: 'horas-v3-500f4',
    storageBucket: 'horas-v3-500f4.appspot.com',
    iosBundleId: 'br.com.i9ja.projeto01',
  );

}